config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to:'users#my_portfolio'
  # get 'search_stock', to:'stocks#search', defaults: { format: 'js' }
  get 'search_stock', to:'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord

    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key], endpoint: 'https://sandbox.iexapis.com/v1')
        # client.price(ticker_symbol)
        begin
            new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
    end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    protect_from_forgery except: :search

    def search
        if params[:stock].present?
          @stock = Stock.new_lookup(params[:stock])
          if @stock
            render 'users/my_portfolio'

            # respond_to do |format|
            #     format.js { render partial: 'users/result1' }
            # end
          else
            respond_to do |format|
                flash.now[:alert] = "Please enter a valid symbol to search"
                format.js { render partial: 'users/result1' }
            end
            # redirect_to my_portfolio_path
          end    
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a symbol to search"
                format.js { render partial: 'users/result1' }
            end
        #   redirect_to my_portfolio_path
        end
      end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index

    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success alert-dismissible fade show'>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger alert-dismissible fade show'>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <%= link_to 'FinanceTracker', root_path, class: 'navbar-brand' %>
        <% if current_user %> 
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                        <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <ul class='navbar-nav ml-auto'>
                    <li class='nav-item'>
                        <%= link_to("Logout", destroy_user_session_path,
                            class: "btn btn-xs btn-danger me-1", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to Sign Out?"})%>
                    </li>
                </ul>
                <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @tracked_stocks.each do |stock| %>
            <tr>
                <th scope="row"><%= stock.ticker %></th>
                <td><%= stock.name %></td>
                <td><%= stock.last_price %></td>
                <td><%= 'Action placeholder' %></td>
                <%# <td><%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                                            class: 'btn btn-sm btn-warning' %></td> 
            </tr>
            <% end %>
        </tbody>
        </table>
    </div>
</div>

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block mt-3">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
  </div>
<% end %> 

app/views/users/_result1.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result' %>' 

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class='pt-5'>
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote:true, method: :get, 'data-turbo': true do %>
   <%# <%= form_with url: search_stock_path, method: :get do %> 
    <div class="form-group row">
      <div class="col-sm-9 pe-0">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 ps-0">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

<%= render 'users/result' %>
<%# <div id="results">
    
</div> %>


<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list'%>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Finance Tracker App</h1>

<%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to Sign Out?"}%>